[package]
name = "VoiceAssistant"
version = "0.1.0"
edition = "2021"

[dependencies]
vosk = "0.3.1"
cpal="0.15.3"
winapi={version="0.3", features = ["winbase"]}
cc="1.1.21"
bindgen="0.70.1"
serde={version="1.0.210", features = ["derive"]}
serde_json = "1.0.128"
rubato="0.15.0"


